### ISSUE TITLE
Error during server communication

### ISSUE THREAD

**Issue by WELPXD** [BeatFinder/website#1]
I love your service and I've been using it for a while now. But recently, I've been getting this error: "Error during server communication."
![error](https://cloud.githubusercontent.com/assets/23231201/19958066/daeab690-a150-11e6-8ab3-f9a10c6db6a4.JPG)
I was wondering if you guys know why this error shows up.

Thxs

**Comment by ypperlig** [comment]
Hi,
Sorry for that. Website is now up and running again.
Also, we are shipping out a new version within the next couple of days that will improve the website dramatically (as well as fix the issue you experienced).

**Comment by WELPXD** [comment]
Hey thanks for the update. I see that its work perfectly now.
However, where did the "Upload file" option go?

**Comment by WELPXD** [comment]
Hey thanks for the update. The website is working perfectly now.
However, where did the "Upload file" option go?

**Comment by ypperlig** [comment]
Hi,
We removed the upload function in the current version. We might add support for it later, but at the moment it is not prioritized.
